### ISSUE TITLE
FYI, export_stats.py doesn't work as expected 

### ISSUE THREAD

**Issue by peteyreplies** [MuckRock/API-examples#2]
Just tried to run it on user GeoCen, got back a CSV file with only header rows and nothing else (http://cl.ly/2l0b1p0t2k1D).

**Comment by morisy** [comment]
That's weird; I just ran it and it went fine. Only thing I can think is it might have to do with a permissions issue since by default, the Stats script tries to grab data only admins can see? Can you try limiting it to only publicly available fields, which you can check out here:

https://www.muckrock.com/api_v1/statistics/
