### ISSUE TITLE
Significant amount of public information accessible over API

### ISSUE THREAD

**Issue by red-bin** [MuckRock/API-examples#6]
The API exposes a large amount of information including addresses, phone numbers, first/last names, etc. While much of this information is public record by being sent along with requests, many of those individuals may have privacy concerns because of the ease of access.  Particularly for those who don't know that this is easily possible. This is a reservation that prevents me from going through Muckrock for >100 requests.

**Comment by morisy** [comment]
Hi! Thanks for the head's up on this. I missed this bug report until was searching through the issue you reported on Slack, and very sorry about that.

Most of the fields (address, phone, etc.) were deprecated and originally public by design (and optional for users), but emails shouldn't have been public. Since the public data is deprecated, we've locked down that API access to admin only.
